name: aup-kanban

services:
  aup-kanban:
    image: ip2-kanban-cli:local
    build:
      context: ../..
      dockerfile: tools/kanban-container/Dockerfile.kanban
    restart: always
    container_name: aup-kanban-1
    network_mode: "bridge"
    environment:
      - EXAMPLE_CONFIG=/test/test
    init: true
    user: "${KANBAN_UID:-1000}:${KANBAN_GID:-1000}"
    working_dir: /workspace
    volumes:
      - ../..:/workspace
