use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::SystemTime;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let web_root = manifest_dir.join("../../web");
    let client_root = web_root.clone();
    let source = client_root.join("dist");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let destination = out_dir.join("web-assets");

    emit_rerun_triggers(&web_root, &client_root);

    if client_root.join("package.json").is_file() {
        build_web_client_if_needed(&web_root, &client_root, &source);
    }

    let _ = fs::remove_dir_all(&destination);
    fs::create_dir_all(&destination).expect("create embedded web asset directory");
    if source.join("index.html").is_file() {
        copy_dir(&source, &destination).expect("copy kanban web assets");
    } else {
        write_fallback_index(&destination).expect("write fallback kanban web asset");
        println!(
            "cargo:warning=kanban web/dist not found after build; embedding fallback web page"
        );
    }

    // US-034: precompress and fingerprint the embedded assets once, at build
    // time. Compressing per request would repeat identical work forever, and a
    // runtime hash would either cost a SHA-256 over the whole asset on every
    // request or reintroduce a lazily populated global cache.
    let manifest = build_asset_manifest(&destination).expect("build asset manifest");
    fs::write(out_dir.join("asset_manifest.rs"), manifest).expect("write asset manifest");

    println!(
        "cargo:rustc-env=KANBAN_WEB_ASSET_DIR={}",
        destination.display()
    );
}

/// Content types that benefit from gzip. Images and fonts are already
/// compressed, so a second pass costs binary size and buys nothing.
const COMPRESSIBLE_EXTENSIONS: [&str; 8] =
    ["html", "js", "mjs", "css", "json", "map", "svg", "txt"];

/// Do not embed a compressed copy that fails to pay for itself.
const MIN_COMPRESSION_SAVING: f64 = 0.10;
/// Compressing a tiny file usually makes it larger.
const MIN_COMPRESSIBLE_BYTES: u64 = 1024;

fn build_asset_manifest(root: &Path) -> io::Result<String> {
    let mut entries = Vec::new();
    collect_assets(root, root, &mut entries)?;
    entries.sort();

    let mut out = String::from(
        "// @generated by crates/web-server/build.rs — do not edit.\n\
         pub(crate) struct AssetMeta {\n\
         pub(crate) path: &'static str,\n\
         pub(crate) etag: &'static str,\n\
         pub(crate) gzip_path: Option<&'static str>,\n\
         pub(crate) gzip_etag: Option<&'static str>,\n\
         }\n\
         pub(crate) static ASSET_MANIFEST: &[AssetMeta] = &[\n",
    );

    for relative in entries {
        let absolute = root.join(&relative);
        let bytes = fs::read(&absolute)?;
        let etag = strong_etag(&bytes);

        let mut gzip_path = "None".to_string();
        let mut gzip_etag = "None".to_string();
        if let Some(compressed) = maybe_compress(&relative, &bytes) {
            let gz_relative = format!("{relative}.gz");
            fs::write(root.join(&gz_relative), &compressed)?;
            gzip_path = format!("Some({gz_relative:?})");
            gzip_etag = format!("Some({:?})", strong_etag(&compressed));
        }

        out.push_str(&format!(
            "    AssetMeta {{ path: {relative:?}, etag: {etag:?}, gzip_path: {gzip_path}, gzip_etag: {gzip_etag} }},\n"
        ));
    }
    out.push_str("];\n");
    Ok(out)
}

fn collect_assets(root: &Path, dir: &Path, out: &mut Vec<String>) -> io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if entry.file_type()?.is_dir() {
            collect_assets(root, &path, out)?;
            continue;
        }
        let relative = path
            .strip_prefix(root)
            .expect("asset lives under the asset root")
            .to_string_lossy()
            .replace('\\', "/");
        // Compressed variants are generated below; never fingerprint one as if
        // it were an independently requestable asset.
        if relative.ends_with(".gz") {
            continue;
        }
        out.push(relative);
    }
    Ok(())
}

fn maybe_compress(relative: &str, bytes: &[u8]) -> Option<Vec<u8>> {
    if (bytes.len() as u64) < MIN_COMPRESSIBLE_BYTES {
        return None;
    }
    let extension = Path::new(relative)
        .extension()
        .and_then(|value| value.to_str())
        .unwrap_or_default()
        .to_ascii_lowercase();
    if !COMPRESSIBLE_EXTENSIONS.contains(&extension.as_str()) {
        return None;
    }

    let mut encoder = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::best());
    io::Write::write_all(&mut encoder, bytes).ok()?;
    let compressed = encoder.finish().ok()?;
    let saving = 1.0 - (compressed.len() as f64 / bytes.len() as f64);
    (saving >= MIN_COMPRESSION_SAVING).then_some(compressed)
}

/// A strong entity-tag over the exact representation bytes.
fn strong_etag(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let digest = Sha256::digest(bytes);
    format!("\"{:x}\"", digest)
}

fn emit_rerun_triggers(web_root: &Path, client_root: &Path) {
    for path in [
        client_root.join("package.json"),
        client_root.join("package-lock.json"),
        client_root.join("tsconfig.json"),
        client_root.join("vite.config.ts"),
        client_root.join("index.html"),
        client_root.join("dist"),
        client_root.join("src"),
        web_root.join("shared"),
    ] {
        println!("cargo:rerun-if-changed={}", path.display());
    }
}

fn build_web_client_if_needed(web_root: &Path, client_root: &Path, dist: &Path) {
    let index = dist.join("index.html");
    if index.is_file() && !web_sources_newer_than(web_root, client_root, &index) {
        return;
    }

    if !client_root.join("node_modules").is_dir() {
        run_npm(client_root, &["install"]);
    }
    run_npm(client_root, &["run", "build"]);
}

fn web_sources_newer_than(web_root: &Path, client_root: &Path, target: &Path) -> bool {
    let target_modified = modified_time(target).unwrap_or(SystemTime::UNIX_EPOCH);
    [
        client_root.join("package.json"),
        client_root.join("package-lock.json"),
        client_root.join("tsconfig.json"),
        client_root.join("vite.config.ts"),
        client_root.join("index.html"),
        client_root.join("src"),
        web_root.join("shared"),
    ]
    .iter()
    .filter_map(|path| newest_modified_time(path).ok().flatten())
    .any(|modified| modified > target_modified)
}

fn newest_modified_time(path: &Path) -> io::Result<Option<SystemTime>> {
    if !path.exists() {
        return Ok(None);
    }
    if path.is_file() {
        return modified_time(path).map(Some);
    }

    let mut newest = modified_time(path).ok();
    for entry in fs::read_dir(path)? {
        let entry = entry?;
        let child = entry.path();
        if child
            .file_name()
            .is_some_and(|name| name == "node_modules" || name == "dist")
        {
            continue;
        }
        if let Some(modified) = newest_modified_time(&child)?
            && newest.is_none_or(|current| modified > current)
        {
            newest = Some(modified);
        }
    }
    Ok(newest)
}

fn modified_time(path: &Path) -> io::Result<SystemTime> {
    fs::metadata(path)?.modified()
}

fn run_npm(current_dir: &Path, args: &[&str]) {
    let status = Command::new(npm_program())
        .args(args)
        .current_dir(current_dir)
        .status()
        .unwrap_or_else(|error| {
            panic!(
                "failed to run npm {} in {}: {error}",
                args.join(" "),
                current_dir.display()
            )
        });
    if !status.success() {
        panic!(
            "npm {} failed with status {status} in {}",
            args.join(" "),
            current_dir.display()
        );
    }
}

fn npm_program() -> &'static str {
    if cfg!(windows) { "npm.cmd" } else { "npm" }
}

fn copy_dir(source: &Path, destination: &Path) -> io::Result<()> {
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let source_path = entry.path();
        let destination_path = destination.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            fs::create_dir_all(&destination_path)?;
            copy_dir(&source_path, &destination_path)?;
        } else {
            fs::copy(&source_path, &destination_path)?;
        }
    }
    Ok(())
}

fn write_fallback_index(destination: &Path) -> io::Result<()> {
    fs::write(
        destination.join("index.html"),
        r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>kanban web assets missing</title>
  </head>
  <body>
    <main>
      <h1>kanban web assets missing</h1>
      <p>Build the Vite web app before compiling the kanban binary.</p>
    </main>
  </body>
</html>
"#,
    )
}
