//! Embedded static asset delivery (`US-034`).
//!
//! The previous implementation set `Content-Type` and nothing else, so every
//! navigation re-downloaded the entire JavaScript bundle even though Vite
//! filenames are content-hashed and can never change meaning. It also copied
//! each asset's bytes into a fresh `Vec` per request, and answered unknown
//! `/api/*` paths with `200 index.html` instead of `404`.
//!
//! This module adds, per RFC 9110:
//!
//! - `Cache-Control`, immutable for content-hashed assets and `no-cache` for the
//!   SPA entry document, which must always be revalidated so a new build is
//!   picked up immediately;
//! - a strong `ETag` computed at build time, distinct per content-coding, and
//!   `304 Not Modified` on `If-None-Match`;
//! - `Accept-Ranges: bytes`, `206 Partial Content` with `Content-Range`, and
//!   `416` for unsatisfiable ranges, honoring `If-Range`;
//! - `Content-Encoding: gzip` negotiation against representations compressed at
//!   build time, with `Vary: Accept-Encoding`.
//!
//! Compression happens in `build.rs` rather than in a runtime middleware layer.
//! The assets are embedded and never change at runtime, so compressing once per
//! build instead of once per request is strictly better; it yields a stable
//! strong validator per representation; and it sidesteps the range-versus-
//! compression interaction entirely, because a range is always served against
//! the stored representation the client actually negotiated.

use axum::body::{Body, Bytes};
use axum::http::{HeaderMap, HeaderValue, StatusCode, Uri, header};
use axum::response::{IntoResponse, Response};
use include_dir::{Dir, include_dir};

static WEB_ASSETS: Dir<'_> = include_dir!("$KANBAN_WEB_ASSET_DIR");

// Build-time asset metadata: strong ETags per representation, plus the
// precompressed variant when one was worth embedding. Generated by `build.rs`
// as `AssetMeta` + `ASSET_MANIFEST`, sorted by `path`.
include!(concat!(env!("OUT_DIR"), "/asset_manifest.rs"));

/// Vite writes content-hashed filenames under this prefix. A hashed name can
/// never denote different bytes, so it is safe to cache for a year.
const HASHED_ASSET_PREFIX: &str = "assets/";
const IMMUTABLE: &str = "public, max-age=31536000, immutable";
/// The entry document is not content-hashed: it is the thing that points at the
/// hashed assets, so it must be revalidated on every navigation.
const ENTRY_DOCUMENT: &str = "no-cache";
const SHORT_LIVED: &str = "public, max-age=300";

const INDEX_PATH: &str = "index.html";

fn manifest_entry(path: &str) -> Option<&'static AssetMeta> {
    ASSET_MANIFEST
        .binary_search_by(|entry| entry.path.cmp(path))
        .ok()
        .map(|index| &ASSET_MANIFEST[index])
}

fn cache_control_for(path: &str) -> &'static str {
    if path == INDEX_PATH {
        ENTRY_DOCUMENT
    } else if path.starts_with(HASHED_ASSET_PREFIX) {
        IMMUTABLE
    } else {
        SHORT_LIVED
    }
}

/// The representation selected for a request: identity or gzip.
struct Representation {
    body: Bytes,
    etag: &'static str,
    encoding: Option<&'static str>,
}

fn accepts_gzip(headers: &HeaderMap) -> bool {
    headers
        .get(header::ACCEPT_ENCODING)
        .and_then(|value| value.to_str().ok())
        .is_some_and(|value| {
            value.split(',').any(|item| {
                let mut parts = item.split(';');
                let coding = parts.next().unwrap_or("").trim();
                if !coding.eq_ignore_ascii_case("gzip") && coding != "*" {
                    return false;
                }
                // `gzip;q=0` explicitly refuses the coding.
                !parts.any(|param| param.trim().replace(' ', "") == "q=0")
            })
        })
}

fn select_representation(path: &str, headers: &HeaderMap) -> Option<Representation> {
    let meta = manifest_entry(path)?;
    if accepts_gzip(headers)
        && let (Some(gzip_path), Some(gzip_etag)) = (meta.gzip_path, meta.gzip_etag)
        && let Some(file) = WEB_ASSETS.get_file(gzip_path)
    {
        return Some(Representation {
            body: Bytes::from_static(file.contents()),
            etag: gzip_etag,
            encoding: Some("gzip"),
        });
    }
    let file = WEB_ASSETS.get_file(path)?;
    Some(Representation {
        // `Bytes::from_static` borrows the embedded bytes instead of allocating
        // a fresh copy of every asset on every request.
        body: Bytes::from_static(file.contents()),
        etag: meta.etag,
        encoding: None,
    })
}

/// A single byte range from a `Range: bytes=...` header field.
#[derive(Debug, PartialEq, Eq)]
enum RangeSpec {
    /// `bytes=<first>-<last>` or `bytes=<first>-`
    FromTo(u64, Option<u64>),
    /// `bytes=-<suffix-length>`
    Suffix(u64),
}

/// Parse a single-range `Range` field value.
///
/// Multi-range requests return `None`: serving the full representation with
/// `200` is always a valid response to a `Range` request, and multipart range
/// responses buy nothing for embedded UI assets.
fn parse_range(value: &str) -> Option<RangeSpec> {
    let spec = value.trim().strip_prefix("bytes=")?.trim();
    if spec.contains(',') {
        return None;
    }
    let (first, last) = spec.split_once('-')?;
    let (first, last) = (first.trim(), last.trim());
    if first.is_empty() {
        let suffix = last.parse::<u64>().ok()?;
        return Some(RangeSpec::Suffix(suffix));
    }
    let first = first.parse::<u64>().ok()?;
    let last = if last.is_empty() {
        None
    } else {
        Some(last.parse::<u64>().ok()?)
    };
    Some(RangeSpec::FromTo(first, last))
}

/// Resolve a range against a representation length.
///
/// Returns `Err(())` when the range is unsatisfiable (`416`), and `Ok(None)`
/// when the range should be ignored and the full representation served.
fn resolve_range(spec: &RangeSpec, length: u64) -> Result<Option<(u64, u64)>, ()> {
    match *spec {
        RangeSpec::Suffix(0) => Err(()),
        RangeSpec::Suffix(suffix) => {
            let start = length.saturating_sub(suffix);
            if length == 0 {
                return Err(());
            }
            Ok(Some((start, length - 1)))
        }
        RangeSpec::FromTo(first, _) if first >= length => Err(()),
        RangeSpec::FromTo(first, last) => {
            let last = last.unwrap_or(length - 1).min(length - 1);
            if last < first {
                return Err(());
            }
            Ok(Some((first, last)))
        }
    }
}

/// `If-None-Match` matches when any listed entity-tag equals ours, or when the
/// field is `*`. Weak comparison is used, as RFC 9110 requires for `If-None-Match`.
fn if_none_match_matches(headers: &HeaderMap, etag: &str) -> bool {
    let Some(value) = headers
        .get(header::IF_NONE_MATCH)
        .and_then(|value| value.to_str().ok())
    else {
        return false;
    };
    if value.trim() == "*" {
        return true;
    }
    value
        .split(',')
        .map(|candidate| candidate.trim().trim_start_matches("W/"))
        .any(|candidate| candidate == etag)
}

fn set(response: &mut Response, name: header::HeaderName, value: &str) {
    if let Ok(value) = HeaderValue::from_str(value) {
        response.headers_mut().insert(name, value);
    }
}

pub(crate) fn serve(uri: &Uri, headers: &HeaderMap) -> Response {
    let requested = uri.path().trim_start_matches('/');

    // An unknown `/api/*` path is a routing mistake, not a client-side route.
    // Falling back to `index.html` with `200` here made every typo'd or removed
    // endpoint look like a successful HTML response to any API client.
    if requested.starts_with("api/") || requested == "api" {
        return (StatusCode::NOT_FOUND, "not found").into_response();
    }

    let path = if requested.is_empty() {
        INDEX_PATH
    } else {
        requested
    };
    // SPA fallback: an unknown non-API path is a client-side route.
    let path = if WEB_ASSETS.get_file(path).is_some() {
        path
    } else {
        INDEX_PATH
    };

    let Some(representation) = select_representation(path, headers) else {
        return (StatusCode::NOT_FOUND, "kanban web assets are not embedded").into_response();
    };

    let mime = mime_guess::from_path(path).first_or_octet_stream();
    let cache_control = cache_control_for(path);

    if if_none_match_matches(headers, representation.etag) {
        let mut response = StatusCode::NOT_MODIFIED.into_response();
        decorate(&mut response, &representation, cache_control);
        return response;
    }

    let length = representation.body.len() as u64;
    let range = headers
        .get(header::RANGE)
        .and_then(|value| value.to_str().ok())
        .filter(|_| if_range_matches(headers, representation.etag))
        .and_then(parse_range);

    let mut response = match range {
        Some(spec) => match resolve_range(&spec, length) {
            Err(()) => {
                let mut response = StatusCode::RANGE_NOT_SATISFIABLE.into_response();
                set(
                    &mut response,
                    header::CONTENT_RANGE,
                    &format!("bytes */{length}"),
                );
                decorate(&mut response, &representation, cache_control);
                return response;
            }
            Ok(None) => full_response(&representation),
            Ok(Some((start, end))) => {
                let slice = representation
                    .body
                    .slice(start as usize..(end as usize + 1));
                let mut response = (StatusCode::PARTIAL_CONTENT, Body::from(slice)).into_response();
                set(
                    &mut response,
                    header::CONTENT_RANGE,
                    &format!("bytes {start}-{end}/{length}"),
                );
                response
            }
        },
        None => full_response(&representation),
    };

    set(&mut response, header::CONTENT_TYPE, mime.as_ref());
    decorate(&mut response, &representation, cache_control);
    response
}

fn full_response(representation: &Representation) -> Response {
    Body::from(representation.body.clone()).into_response()
}

/// Headers that must appear on every response for a representation, including
/// `304` and `416`, which carry no body.
fn decorate(response: &mut Response, representation: &Representation, cache_control: &str) {
    set(response, header::CACHE_CONTROL, cache_control);
    set(response, header::ETAG, representation.etag);
    set(response, header::ACCEPT_RANGES, "bytes");
    // The response body depends on `Accept-Encoding`, so shared caches must key
    // on it.
    set(response, header::VARY, "accept-encoding");
    if let Some(encoding) = representation.encoding {
        set(response, header::CONTENT_ENCODING, encoding);
    }
}

/// `If-Range` uses strong comparison: if the client's validator no longer
/// matches, the range must be ignored and the full representation returned.
fn if_range_matches(headers: &HeaderMap, etag: &str) -> bool {
    match headers
        .get(header::IF_RANGE)
        .and_then(|value| value.to_str().ok())
    {
        None => true,
        Some(value) => value.trim() == etag,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn get(path: &str, headers: HeaderMap) -> Response {
        serve(&path.parse::<Uri>().unwrap(), &headers)
    }

    fn header_of(response: &Response, name: header::HeaderName) -> Option<String> {
        response
            .headers()
            .get(name)
            .and_then(|value| value.to_str().ok())
            .map(str::to_string)
    }

    /// The first hashed asset in the manifest, if the web app was built.
    fn hashed_asset() -> Option<&'static AssetMeta> {
        ASSET_MANIFEST
            .iter()
            .find(|entry| entry.path.starts_with(HASHED_ASSET_PREFIX))
    }

    #[test]
    fn hashed_assets_are_immutable_and_carry_a_strong_etag() {
        let Some(asset) = hashed_asset() else {
            return; // web assets not built in this environment
        };
        let response = get(&format!("/{}", asset.path), HeaderMap::new());
        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            header_of(&response, header::CACHE_CONTROL).as_deref(),
            Some(IMMUTABLE)
        );
        assert_eq!(
            header_of(&response, header::ETAG).as_deref(),
            Some(asset.etag)
        );
        assert_eq!(
            header_of(&response, header::ACCEPT_RANGES).as_deref(),
            Some("bytes")
        );
    }

    #[test]
    fn entry_document_is_revalidated_on_every_navigation() {
        let response = get("/", HeaderMap::new());
        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            header_of(&response, header::CACHE_CONTROL).as_deref(),
            Some(ENTRY_DOCUMENT),
            "index.html must never be cached immutably or a new build is invisible"
        );
    }

    /// B11: a repeat load of an unchanged hashed asset transfers zero bytes.
    #[test]
    fn matching_if_none_match_returns_304_with_no_body() {
        let Some(asset) = hashed_asset() else {
            return;
        };
        let mut headers = HeaderMap::new();
        headers.insert(
            header::IF_NONE_MATCH,
            HeaderValue::from_str(asset.etag).unwrap(),
        );
        let response = get(&format!("/{}", asset.path), headers);
        assert_eq!(response.status(), StatusCode::NOT_MODIFIED);
        assert_eq!(
            header_of(&response, header::ETAG).as_deref(),
            Some(asset.etag)
        );
        assert_eq!(
            header_of(&response, header::CACHE_CONTROL).as_deref(),
            Some(IMMUTABLE)
        );
    }

    #[test]
    fn stale_if_none_match_returns_the_full_representation() {
        let Some(asset) = hashed_asset() else {
            return;
        };
        let mut headers = HeaderMap::new();
        headers.insert(header::IF_NONE_MATCH, HeaderValue::from_static("\"stale\""));
        let response = get(&format!("/{}", asset.path), headers);
        assert_eq!(response.status(), StatusCode::OK);
    }

    #[test]
    fn valid_range_returns_206_with_content_range() {
        let Some(asset) = hashed_asset() else {
            return;
        };
        let mut headers = HeaderMap::new();
        headers.insert(header::RANGE, HeaderValue::from_static("bytes=0-9"));
        let response = get(&format!("/{}", asset.path), headers);
        assert_eq!(response.status(), StatusCode::PARTIAL_CONTENT);
        let content_range = header_of(&response, header::CONTENT_RANGE).unwrap();
        assert!(
            content_range.starts_with("bytes 0-9/"),
            "unexpected Content-Range: {content_range}"
        );
    }

    #[test]
    fn unsatisfiable_range_returns_416_with_the_representation_length() {
        let Some(asset) = hashed_asset() else {
            return;
        };
        let mut headers = HeaderMap::new();
        headers.insert(
            header::RANGE,
            HeaderValue::from_static("bytes=99999999-99999999"),
        );
        let response = get(&format!("/{}", asset.path), headers);
        assert_eq!(response.status(), StatusCode::RANGE_NOT_SATISFIABLE);
        assert!(
            header_of(&response, header::CONTENT_RANGE)
                .unwrap()
                .starts_with("bytes */")
        );
    }

    #[test]
    fn gzip_is_served_only_when_accepted_and_varies_on_accept_encoding() {
        let Some(asset) = ASSET_MANIFEST
            .iter()
            .find(|entry| entry.gzip_path.is_some())
        else {
            return;
        };

        let plain = get(&format!("/{}", asset.path), HeaderMap::new());
        assert_eq!(header_of(&plain, header::CONTENT_ENCODING), None);
        assert_eq!(header_of(&plain, header::ETAG).as_deref(), Some(asset.etag));

        let mut headers = HeaderMap::new();
        headers.insert(header::ACCEPT_ENCODING, HeaderValue::from_static("gzip"));
        let compressed = get(&format!("/{}", asset.path), headers);
        assert_eq!(
            header_of(&compressed, header::CONTENT_ENCODING).as_deref(),
            Some("gzip")
        );
        assert_eq!(
            header_of(&compressed, header::ETAG).as_deref(),
            asset.gzip_etag,
            "each content-coding must have its own strong validator"
        );
        assert_eq!(
            header_of(&compressed, header::VARY).as_deref(),
            Some("accept-encoding")
        );
    }

    #[test]
    fn gzip_is_refused_when_the_client_sets_q_zero() {
        let mut headers = HeaderMap::new();
        headers.insert(
            header::ACCEPT_ENCODING,
            HeaderValue::from_static("gzip;q=0, identity"),
        );
        assert!(!accepts_gzip(&headers));
    }

    #[test]
    fn unknown_client_route_falls_back_to_the_spa_document() {
        let response = get("/backlog", HeaderMap::new());
        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            header_of(&response, header::CONTENT_TYPE).as_deref(),
            Some("text/html")
        );
    }

    /// Regression: an unrouted `/api/*` path must not be answered with the SPA
    /// document and a `200`.
    #[test]
    fn unknown_api_path_returns_404() {
        for path in ["/api/does-not-exist", "/api/progress", "/api"] {
            let response = get(path, HeaderMap::new());
            assert_eq!(
                response.status(),
                StatusCode::NOT_FOUND,
                "{path} must not fall back to index.html"
            );
        }
    }

    #[test]
    fn parse_range_handles_the_documented_forms() {
        assert_eq!(
            parse_range("bytes=0-9"),
            Some(RangeSpec::FromTo(0, Some(9)))
        );
        assert_eq!(parse_range("bytes=10-"), Some(RangeSpec::FromTo(10, None)));
        assert_eq!(parse_range("bytes=-500"), Some(RangeSpec::Suffix(500)));
        assert_eq!(
            parse_range("bytes=0-9,20-29"),
            None,
            "multi-range is ignored"
        );
        assert_eq!(parse_range("items=0-9"), None);
        assert_eq!(parse_range("bytes=abc"), None);
    }

    #[test]
    fn resolve_range_clamps_and_rejects() {
        assert_eq!(
            resolve_range(&RangeSpec::FromTo(0, Some(9)), 100),
            Ok(Some((0, 9)))
        );
        assert_eq!(
            resolve_range(&RangeSpec::FromTo(90, Some(500)), 100),
            Ok(Some((90, 99))),
            "a last-byte-pos past the end is clamped, not rejected"
        );
        assert_eq!(resolve_range(&RangeSpec::FromTo(100, None), 100), Err(()));
        assert_eq!(resolve_range(&RangeSpec::FromTo(9, Some(4)), 100), Err(()));
        assert_eq!(
            resolve_range(&RangeSpec::Suffix(10), 100),
            Ok(Some((90, 99)))
        );
        assert_eq!(
            resolve_range(&RangeSpec::Suffix(500), 100),
            Ok(Some((0, 99))),
            "a suffix longer than the representation yields the whole thing"
        );
        assert_eq!(resolve_range(&RangeSpec::Suffix(0), 100), Err(()));
    }

    #[test]
    fn if_range_mismatch_ignores_the_range() {
        let Some(asset) = hashed_asset() else {
            return;
        };
        let mut headers = HeaderMap::new();
        headers.insert(header::RANGE, HeaderValue::from_static("bytes=0-9"));
        headers.insert(header::IF_RANGE, HeaderValue::from_static("\"other\""));
        let response = get(&format!("/{}", asset.path), headers);
        assert_eq!(
            response.status(),
            StatusCode::OK,
            "a stale If-Range must produce the full representation"
        );
    }
}
