use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use ts_rs::{Config, TS};

use crate::dto::{
    ConfigResponse, GitPullResponse, GitPushResponse, GitStatusResponse, PhaseSummary,
    ProjectProgress, RepositorySnapshot, StoryPointsResponse, WebEpic, WebEpicDetail,
    WebReportDashboard, WebReportEstimate, WebReportPhaseRow, WebReportProgress,
    WebReportSprintProjection, WebReportWbsRow, WebSprint, WebStory, WebStoryDetail, WebTask,
    WebTaskSummary, WebTeamMember,
};
use crate::metrics::{
    BurndownPoint, BurnupPoint, DashboardMetrics, Forecast, ForecastCompletion, ForecastThroughput,
    LeadTimePoint, VelocityPoint,
};

const GENERATED_PATH: &str = "../../web/shared/generated/api.ts";
const SPRINT_STATUSES: [&str; 4] = ["planned", "active", "closed", "cancelled"];

fn generated_api_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(GENERATED_PATH)
}

fn ts_config() -> Config {
    Config::new().with_large_int("number")
}

fn render_union(name: &str, values: &[&str]) -> String {
    let mut out = format!("export type {name} =\n");
    for (index, value) in values.iter().enumerate() {
        let suffix = if index + 1 == values.len() {
            ";\n\n"
        } else {
            "\n"
        };
        out.push_str(&format!("  | \"{value}\"{suffix}"));
    }
    out
}

fn render_array(name: &str, ty: &str, values: &[&str]) -> String {
    let body = values
        .iter()
        .map(|value| format!("\"{value}\""))
        .collect::<Vec<_>>()
        .join(", ");
    format!("export const {name}: {ty}[] = [{body}];\n\n")
}

fn generated_declarations(cfg: &Config) -> Vec<String> {
    vec![
        export_declaration(WebTask::decl(cfg)),
        export_declaration(WebTaskSummary::decl(cfg)),
        export_declaration(WebStory::decl(cfg)),
        export_declaration(WebStoryDetail::decl(cfg)),
        export_declaration(WebSprint::decl(cfg)),
        export_declaration(WebEpic::decl(cfg)),
        export_declaration(WebEpicDetail::decl(cfg)),
        export_declaration(PhaseSummary::decl(cfg)),
        export_declaration(ProjectProgress::decl(cfg)),
        export_declaration(RepositorySnapshot::decl(cfg)),
        export_declaration(BurndownPoint::decl(cfg)),
        export_declaration(BurnupPoint::decl(cfg)),
        export_declaration(LeadTimePoint::decl(cfg)),
        export_declaration(VelocityPoint::decl(cfg)),
        export_declaration(ForecastThroughput::decl(cfg)),
        export_declaration(ForecastCompletion::decl(cfg)),
        export_declaration(Forecast::decl(cfg)),
        export_declaration(DashboardMetrics::decl(cfg)),
        export_declaration(WebReportEstimate::decl(cfg)),
        export_declaration(WebReportWbsRow::decl(cfg)),
        export_declaration(WebReportPhaseRow::decl(cfg)),
        export_declaration(WebReportSprintProjection::decl(cfg)),
        export_declaration(WebReportProgress::decl(cfg)),
        export_declaration(WebReportDashboard::decl(cfg)),
        export_declaration(StoryPointsResponse::decl(cfg)),
        export_declaration(ConfigResponse::decl(cfg)),
        export_declaration(GitPullResponse::decl(cfg)),
        export_declaration(GitStatusResponse::decl(cfg)),
        export_declaration(GitPushResponse::decl(cfg)),
        export_declaration(WebTeamMember::decl(cfg)),
    ]
}

fn export_declaration(declaration: String) -> String {
    if let Some(rest) = declaration.strip_prefix("type ") {
        format!("export type {rest}")
    } else if let Some(rest) = declaration.strip_prefix("interface ") {
        format!("export interface {rest}")
    } else {
        declaration
    }
}

fn render_generated_api() -> String {
    let cfg = ts_config();
    let mut out = String::from(
        "// Generated by `cargo test -p kanban-web-server export_bindings -- --exact`.\n// Do not edit by hand.\n\n",
    );
    out.push_str(&render_union(
        "StoryStatus",
        &kanban_core::SPRINT_STATUS_DISPLAY_ORDER,
    ));
    out.push_str(&render_array(
        "STORY_STATUSES",
        "StoryStatus",
        &kanban_core::SPRINT_STATUS_DISPLAY_ORDER,
    ));
    out.push_str(&render_union(
        "StoryLifecycleStatus",
        &kanban_core::CANONICAL_STORY_STATUSES,
    ));
    out.push_str(&render_array(
        "STORY_LIFECYCLE_STATUSES",
        "StoryLifecycleStatus",
        &kanban_core::CANONICAL_STORY_STATUSES,
    ));
    out.push_str(&render_union("SprintStatus", &SPRINT_STATUSES));
    out.push_str(&render_array(
        "SPRINT_STATUSES",
        "SprintStatus",
        &SPRINT_STATUSES,
    ));
    out.push_str(&render_union(
        "TaskStatus",
        &kanban_core::CANONICAL_TASK_STATUSES,
    ));
    out.push_str(&render_array(
        "TASK_STATUSES",
        "TaskStatus",
        &kanban_core::CANONICAL_TASK_STATUSES,
    ));
    for declaration in generated_declarations(&cfg) {
        out.push_str(&declaration);
        out.push_str("\n\n");
    }
    out
}

fn write_generated_api(path: &Path) -> Result<()> {
    let content = render_generated_api();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!("create generated TypeScript directory {}", parent.display())
        })?;
    }
    fs::write(path, content)
        .with_context(|| format!("write generated TypeScript bindings to {}", path.display()))
}

#[cfg(test)]
fn typegen_test_lock() -> &'static std::sync::Mutex<()> {
    static LOCK: std::sync::OnceLock<std::sync::Mutex<()>> = std::sync::OnceLock::new();
    LOCK.get_or_init(|| std::sync::Mutex::new(()))
}

#[test]
fn export_bindings() -> Result<()> {
    let _guard = typegen_test_lock().lock().unwrap();
    write_generated_api(&generated_api_path())
}

#[test]
fn generated_bindings_are_current() -> Result<()> {
    let _guard = typegen_test_lock().lock().unwrap();
    let path = generated_api_path();
    let expected = render_generated_api();
    let current = fs::read_to_string(&path)
        .with_context(|| format!("read generated TypeScript bindings from {}", path.display()))?;
    assert_eq!(current, expected, "{} is out of date", path.display());
    Ok(())
}
